export const VITE_API_KEY=""
export const VITE_AUTH_DOMAIN=""
export const VITE_PROJECT_ID=""
export const VITE_STORAGE_BUCKET=""
export const VITE_MESSAGING_SENDER_ID=""
export const VITE_APP_ID=""
export const VITE_DATABASE_URL=""
